### ISSUE TITLE
delivery_options is missing data and a filter

### ISSUE THREAD

**Issue by Maescool** [myparcelbe/api#4]
delivery_options is missing cubee's points
https://cubee.be/nl/
these used to be known as 'bpost automaten', but got rebranded to cubee for multi carrier support last year
also bpost still delivers to them, I believe their API also gives these points, (or at leased they used to) and for future carriers that may come to myparcel, they might use these cubee's to.

**Comment by reindert-vetter** [comment]
We do not receive this information from bpost.
This may be because we also have to send extra information to bpost. It is a nice feature, but after consultation with my colleague, we are not going to build this soon.
